#!/bin/bash

# IMAGE_VERSION=$(echo $DOCKER_TAG | cut -d "-" -f2)

# if [ $DOCKER_TAG == "latest" ]
# then
#   docker build . --build-arg IMAGE_VERSION=${DOCKER_TAG} -t ${IMAGE_NAME}
# else
#   docker build . --build-arg IMAGE_VERSION=${IMAGE_VERSION} -t ${IMAGE_NAME}
# fi

if [ $IMAGE_NAME == "python38-ai" ]
then
  docker build -t ${IMAGE_NAME} .
fi
